version: '3.8'
services:
  nginx:
    image: docker.io/nginx:1-alpine
    ports:
      - 3000:3000
    volumes:
      - ./fake_cache/:/var/www/html/xaccel/restrictedfiles
      - ./nginx.conf:/etc/nginx/nginx.conf
    network-mode: host
    restart: always
